name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
        include:
        - os: ubuntu-latest
          cmake-args: -G Ninja
          build-args: --parallel
          package-file: teeworlds-*-linux_x86_64.tar.xz

        - os: ubuntu-16.04
          cmake-path: /usr/bin/
          build-args: --parallel
          cmake-args: -G Ninja
          package-file: teeworlds-*-linux_x86_64.tar.xz

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Prepare Linux
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake ninja-build libfreetype6-dev libsdl2-dev -y
        git clone --recursive https://github.com/zeroxs/aegis.cpp.git
        cd aegis.cpp
        sudo ./install-deps.sh
        mkdir -p build
        cd build
        cmake .. -DBUILD_EXAMPLES=0
        make
        sudo make install

    - name: Build in release mode
      run: |
        mkdir release
        cd release
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -Werror=dev -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
        ninja teeworlds_srv

    - name: Package
      run: |
        cd release
        ninja package_default
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: teeworlds-${{ matrix.os }}
        path: release/artifacts
